### ISSUE TITLE
Test Fix

### ISSUE THREAD

**Issue by matiaslev** [Karumi/KataLogInLogOutKotlin#1]
Hi!

I'm using your repo to learn about ARROW. and I see a little error on PresenterTest.

the test 
> should hide the log in form and show the log out form if the log in process finished properly

is doing the same as 

> should hide the log out form and show the log in form if the log out process finished properly

it's something really small. But I could create a PR with this fix if you give me permissions.

Thanks! I really enjoyed learning with this Kata.

**Comment by Serchinastico** [comment]
Hi @matiaslev 

I think you can fork the repository and send us a PR from there. We'll be glad to review it and merge it!

Thanks!

**Comment by matiaslev** [comment]
Hi @Serchinastico 

thanks for your answer :) I did it, here is the link https://github.com/Karumi/KataLogInLogOutKotlin/pull/2

Regards!

**Comment by pedrovgs** [comment]
Thanks for the PR, as we've merged it I'm closing this issue 😃
